sudo: false

language: generic

addons:
  postgresql: "9.3"
  apt:
   packages:
   - libgmp-dev

matrix:
  include:
  - env: ARGS="--resolver lts-9"
    compiler: ": #newest lts 9"

before_install:
  # Using compiler above sets CC to an invalid value, so unset it
  - unset CC

  # stack
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - |
    psql <<EOF
    CREATE USER "PROJECTNAME_LOWER" password 'PROJECTNAME';
    CREATE DATABASE "PROJECTNAME_LOWER_test" OWNER "PROJECTNAME_LOWER";

script:
  - stack init $ARGS
  - stack build --test --bench --install-ghc --haddock --no-haddock-deps --jobs 1

cache:
  directories:
    - $HOME/.stack
